type Defensive = {
  spellId: number;
  name: string;
  baseCd: number;
  cdReduction: boolean;
  charges: boolean;
  spec: string | null;
};

type ClassDefensive = {
  class: string;
  defensives: Defensive[];
};

const DEFENSIVES: ClassDefensive[] = [
  {
    class: "Death Knight",
    defensives: [
      {
        spellId: 48743,
        name: "Death Pact",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 49039,
        name: "Lichborne",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 48792,
        name: "Icebound Fortitude",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 51052,
        name: "Anti-Magic Zone",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 48707,
        name: "Anti-Magic Shell",
        baseCd: 60000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 49998,
        name: "Death Strike",
        baseCd: 0,
        cdReduction: false,
        charges: false,
        spec: null,
      },
    ],
  },
  {
    class: "Demon Hunter",
    defensives: [
      {
        spellId: 196718,
        name: "Darkness",
        baseCd: 300000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 196555,
        name: "Netherwalk",
        baseCd: 180000,
        cdReduction: false,
        charges: false,
        spec: "Havoc",
      },
      {
        spellId: 198589,
        name: "Blur",
        baseCd: 60000,
        cdReduction: false,
        charges: false,
        spec: "Havoc",
      },
    ],
  },
  {
    class: "Druid",
    defensives: [
      {
        spellId: 319454,
        name: "Heart of the Wild",
        baseCd: 300000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 108238,
        name: "Renewal",
        baseCd: 90000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 124974,
        name: "Nature's Vigil",
        baseCd: 90000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 22812,
        name: "Barkskin",
        baseCd: 60000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 22842,
        name: "Frenzied Regeneration",
        baseCd: 36000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 5487,
        name: "Bear Form",
        baseCd: 0,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 61336,
        name: "Feral Instincts",
        baseCd: 180000,
        cdReduction: false,
        charges: false,
        spec: "Feral",
      },
    ],
  },
  {
    class: "Evoker",
    defensives: [
      {
        spellId: 374227,
        name: "Zephyr",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 363916,
        name: "Obsidian Scales",
        baseCd: 90000,
        cdReduction: true,
        charges: true,
        spec: null,
      },
      {
        spellId: 374348,
        name: "Renewing Blaze",
        baseCd: 90000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 360827,
        name: "Blistering Scales",
        baseCd: 30000,
        cdReduction: false,
        charges: false,
        spec: "Augmentation",
      },
    ],
  },
  {
    class: "Hunter",
    defensives: [
      {
        spellId: 186265,
        name: "Aspect of the Turtle",
        baseCd: 180000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 109304,
        name: "Exhilaration",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 264735,
        name: "Survival of the Fittest",
        baseCd: 120000,
        cdReduction: true,
        charges: true,
        spec: null,
      },
      {
        spellId: 388035,
        name: "Fortitude of the Bear",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
    ],
  },
  {
    class: "Mage",
    defensives: [
      {
        spellId: 414658,
        name: "Ice Cold",
        baseCd: 240000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 45438,
        name: "Ice Block",
        baseCd: 240000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 55342,
        name: "Mirror Image",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 110960,
        name: "Greater Invisibility",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 414660,
        name: "Mass Barrier",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 342245,
        name: "Alter Time",
        baseCd: 60000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 342247,
        name: "Alter Time",
        baseCd: 60000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 235450,
        name: "Prismatic Barrier",
        baseCd: 25000,
        cdReduction: false,
        charges: false,
        spec: "Arcane",
      },
      {
        spellId: 235313,
        name: "Blazing Barrier",
        baseCd: 25000,
        cdReduction: false,
        charges: false,
        spec: "Fire",
      },
      {
        spellId: 235219,
        name: "Cold Snap",
        baseCd: 300000,
        cdReduction: false,
        charges: false,
        spec: "Frost",
      },
      {
        spellId: 11426,
        name: "Frost Barrier",
        baseCd: 25000,
        cdReduction: false,
        charges: false,
        spec: "Frost",
      },
    ],
  },
  {
    class: "Monk",
    defensives: [
      {
        spellId: 115203,
        name: "Fortifying Brew",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 122783,
        name: "Diffuse Magic",
        baseCd: 90000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 122470,
        name: "Touch of Karma",
        baseCd: 90000,
        cdReduction: false,
        charges: false,
        spec: "Windwalker",
      },
    ],
  },
  {
    class: "Paladin",
    defensives: [
      {
        spellId: 471195,
        name: "Lay on Hands",
        baseCd: 600000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 1022,
        name: "Blessing of Protection",
        baseCd: 300000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 642,
        name: "Divine Shield",
        baseCd: 300000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 6940,
        name: "Blessing of Sacrifice",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 498,
        name: "Divine Protection",
        baseCd: 90000,
        cdReduction: true,
        charges: false,
        spec: "Holy",
      },
      {
        spellId: 403876,
        name: "Divine Protection",
        baseCd: 90000,
        cdReduction: true,
        charges: false,
        spec: "Retribution",
      },
      {
        spellId: 184662,
        name: "Shield of Vengeance",
        baseCd: 90000,
        cdReduction: false,
        charges: false,
        spec: "Retribution",
      },
    ],
  },
  {
    class: "Priest",
    defensives: [
      {
        spellId: 108968,
        name: "Void Shift",
        baseCd: 300000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 15286,
        name: "Vampiric Embrace",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 19236,
        name: "Desperate Prayer",
        baseCd: 90000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 586,
        name: "Fade",
        baseCd: 30000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 47585,
        name: "Dispersion",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: "Shadow",
      },
    ],
  },
  {
    class: "Rogue",
    defensives: [
      {
        spellId: 5277,
        name: "Evasion",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 31224,
        name: "Cloak of Shadows",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 185311,
        name: "Crimson Vial",
        baseCd: 30000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 1966,
        name: "Feint",
        baseCd: 15000,
        cdReduction: true,
        charges: true,
        spec: null,
      },
    ],
  },
  {
    class: "Shaman",
    defensives: [
      {
        spellId: 198103,
        name: "Earth Elemental",
        baseCd: 300000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 108271,
        name: "Astral Shift",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 108281,
        name: "Ancestral Guidance",
        baseCd: 120000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 108270,
        name: "Stone Bulwark Totem",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
    ],
  },
  {
    class: "Warlock",
    defensives: [
      {
        spellId: 104773,
        name: "Unending Resolve",
        baseCd: 180000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 108416,
        name: "Dark Pact",
        baseCd: 60000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 452930,
        name: "Demonic Healthstone",
        baseCd: 60000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 6789,
        name: "Mortal Coil",
        baseCd: 45000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 234153,
        name: "Drain Life",
        baseCd: 0,
        cdReduction: false,
        charges: false,
        spec: null,
      },
    ],
  },
  {
    class: "Warrior",
    defensives: [
      {
        spellId: 383762,
        name: "Bitter Immunity",
        baseCd: 180000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 97462,
        name: "Rallying Cry",
        baseCd: 180000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 202168,
        name: "Impending Victory",
        baseCd: 25000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 23920,
        name: "Spell Reflection",
        baseCd: 25000,
        cdReduction: true,
        charges: false,
        spec: null,
      },
      {
        spellId: 386208,
        name: "Defensive Stance",
        baseCd: 3000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 118038,
        name: "Die by the Sword",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: "Arms",
      },
      {
        spellId: 190456,
        name: "Ignore Pain",
        baseCd: 11000,
        cdReduction: false,
        charges: false,
        spec: "Arms",
      },
      {
        spellId: 184364,
        name: "Enraged Regeneration",
        baseCd: 120000,
        cdReduction: true,
        charges: false,
        spec: "Fury",
      },
    ],
  },
  {
    class: "Everyone",
    defensives: [
      {
        spellId: 6262,
        name: "Healthstone",
        baseCd: 0,
        cdReduction: false,
        charges: false,
        spec: null,
      },
      {
        spellId: 431416,
        name: "Algari Healing Potion",
        baseCd: 300000,
        cdReduction: false,
        charges: false,
        spec: null,
      },
    ],
  },
];

const getClassDefensives = (
  className: string,
  spec: string | null
): Defensive[] => {
  const classData = DEFENSIVES.find((d) => d.class === className);
  if (!classData) {
    return [];
  }
  const classDefensives = spec
    ? classData.defensives.filter((d) => d.spec === spec || d.spec === null)
    : classData.defensives.filter((d) => d.spec === null);

  return classDefensives.concat(
    DEFENSIVES.find((d) => d.class === "Everyone")!.defensives
  );
};

export { getClassDefensives };
